# debug=true
info:
  version: @project.version@

# server config
server:
  port: 1111
  context-path: /

# spring boot actuator
management:
  security:
    enabled: false
  context-path: /actuator

# eureka config
eureka:
  instance:
    health-check-url-path: ${management.context-path}/health
    status-page-url-path: ${management.context-path}/info
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka

# spring config
spring:
  application:
    name: @project.artifactId@
# Date format string or a fully-qualified date format class name. For instance `yyyy-MM-dd HH:mm:ss`
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      indent_output: true


