info:
  name: @project.name@
  version: @project.version@
  description: @project.description@

# server config
server:
  port: 2221
  context-path: /

# spring boot actuator
management:
  security:
    enabled: false

# eureka config
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka

# spring config
spring:
  application:
    name: @project.artifactId@
  jmx:
    default-domain: @project.artifactId@
# Date format string or a fully-qualified date format class name. For instance `yyyy-MM-dd HH:mm:ss`
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      indent_output: true

  cloud:
    config:
      name: @project.artifactId@
      server:
        git:
          uri: https://github.com/smile90/boot-frame-config
          search-paths: config-repo
          username:
          password:

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: SpringCloudConfig
    password: 123456