# debug=true
info:
  version: @project.version@

# server config
server:
  port: 1111
  servlet-path: /

# spring boot actuator
management:
  security:
    enabled: false
  context-path: /actuator

# eureka config
eureka:
  instance:
    ip-address: 127.0.0.1
    health-check-url-path: ${management.context-path}/health
    status-page-url-path: ${management.context-path}/info
  server:
    waitTimeInMsWhenSyncEmpty: 0
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.ip-address}:${server.port}/eureka

# spring config
spring:
  application:
    name: @project.artifactId@
# Date format string or a fully-qualified date format class name. For instance `yyyy-MM-dd HH:mm:ss`
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      indent_output: true