# debug: true
info:
  version: @project.version@

# server config
server:
  port: 8080
  servlet-path: /

# config
spring:
  application:
    name: @project.artifactId@

# Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly.
  http:
    encoding:
      enabled: true   # Enable http encoding support.
      charset: UTF-8

# Date format string or a fully-qualified date format class name. For instance `yyyy-MM-dd HH:mm:ss`
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      indent_output: true

# Spring MVC
  mvc:
    static-path-pattern:  /static/**
    media-types.json: application/json
    view:
      prefix: /WEB-INF/views
      suffix:

# MVC Thymeleaf
  thymeleaf:
    enabled: false
    cache: false

# dataSource
#DATASOURCE
#   schema: classpath:schema.sql
  datasource:
    continueOnError: true
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/frame?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    validation-query: SELECT 1
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

    druid:
      login-enable: true
      login-username: admin
      login-password: 123456
      exclusions: '*.js,*.css,*.gif,*.jpg,*.png,*.ico,/druid/*'