info:
  name: @project.name@
  version: @project.version@
  description: @project.description@

# server config
server:
  port: 80
  context-path: /

# config
spring:
  application:
    name: @project.artifactId@