info:
  name: @project.name@
  version: @project.version@
  description: @project.description@

# config
spring:
  application:
    name: @project.artifactId@
  jmx:
    default-domain: @project.artifactId@