# debug: true
info:
  version: @project.version@

# server config
server:
  port: 1111
  servlet-path: /zipkin-server

# config
spring:
  application:
    name: @project.artifactId@
  jmx:
    default-domain: @project.artifactId@