# debug: true
info:
  version: @project.version@

# server config
server:
  port: 12080
  servlet-path: /
  error:
    include-stacktrace: ALWAYS

# config
spring:
  application:
    name: @project.artifactId@